name: "OpenElect"
services:
    web:
        build: .
        volumes:
            - .:/OpenElect
        ports:
            - "8080:8080"
        env_file: .env
        depends_on:
            - postgres
            - typesense
            - tailwind

    postgres:
        image: "postgres:17"
        env_file: .env
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    typesense:
        image: "typesense/typesense:27.1"
        ports:
            - "8108:8108"
        volumes:
            - typesense:/data
        env_file: .env

    tailwind:
        image: "node:slim"
        working_dir: /OpenElect
        ports:
            - "8082:8082"
        volumes:
            - .:/OpenElect
        tty: true
        command: [ "npx", "tailwindcss", "-i", "./config/styles.css", "-o", "./config/output.css", "--watch" ]

    admin:
        image: "adminer"
        ports:
            - "8081:8080"
        depends_on:
            - postgres

volumes:
    postgres:
    typesense: