name: "OpenElect"
services:
  web:
    image: "golang:1.23"
    working_dir: /OpenElect
    command: go run .
    volumes:
      - .:/OpenElect
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres
      - typesense
    develop:
      watch:
        - action: rebuild
          path: "**/*.go"
        - action: rebuild
          path: "**/*.tmpl"
        - action: rebuild
          path: "**/*.css"
        - action: rebuild
          path: "**/*.js"


  postgres:
    image: "postgres:17"
    env_file: .env
    ports:
      - "5432:5432"

  typesense:
    image: "typesense/typesense:27.1"
    ports:
      - "8108:8108"
    volumes:
      - /opt/homebrew/var/lib/typesense:/data
    env_file: .env