name: "OpenElect"
services:
  web:
    image: "golang:1.23"
    working_dir: /OpenElect
    command: go run main.go
    volumes:
      - .:/OpenElect
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres/postgres?sslmode=disable"
      TYPESENSE_URL: "http://typesense:8108"
      TYPESENSE_API_KEY: xyz
    depends_on:
      - postgres
      - typesense

  postgres:
    image: "postgres:17"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  typesense:
    image: "typesense/typesense:27.1"
    ports:
      - "8108:8108"
    volumes:
      - /opt/homebrew/var/lib/typesense:/data
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: xyz