apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-adminer-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.adminerService.type }}
  selector:
    app: adminer
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.adminerService.ports | toYaml | nindent 2 }}
