apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-openelect-deployment
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.openelectDeployment.replicas }}
  selector:
    matchLabels:
      app: openelect
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: openelect
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        {{- if eq .Values.environment "prod" }}
        - name: GIN_MODE
          value: release
        {{- end }}
        envFrom:
            - secretRef:
                name: {{ .Values.secrets.secretRef }}
        image: {{ .Values.openelectDeployment.openelectWeb.image.repository }}:{{ .Values.openelectDeployment.openelectWeb.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.openelectDeployment.openelectWeb.imagePullPolicy }}
        name: openelect-web
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /OpenElect/config
          name: colors-config
      initContainers:
      - command:
        - sh
        - -c
        - cp /tmp/styles.css /OpenElect/config/styles.css && cp /tmp/colors.json /OpenElect/config/colors.json && cp /tmp/config.yaml /OpenElect/config/config.yaml
          && cp /tmp/output.css /OpenElect/config/output.css
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.openelectDeployment.copyConfigFiles.image.repository }}:{{ .Values.openelectDeployment.copyConfigFiles.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.openelectDeployment.copyConfigFiles.imagePullPolicy
          }}
        name: copy-config-files
        resources: {}
        volumeMounts:
        - mountPath: /OpenElect/config
          name: colors-config
      volumes:
          -   name: colors-config
              persistentVolumeClaim:
                  claimName: {{ include "chart.fullname" . }}-config-pvc
