apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-openelect-deployment
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.openelectDeployment.replicas }}
  selector:
    matchLabels:
      app: openelect
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: openelect
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        {{- if eq .Values.environment "prod" }}
        - name: GIN_MODE
          value: release
        - name: TYPESENSE_URL
          value: {{ include "chart.fullname" . }}-typesense-service
        {{- end }}
        envFrom:
            - secretRef:
                name: {{ .Values.secrets.secretRef }}
        image: {{ .Values.openelectDeployment.openelectWeb.image.repository }}:{{ .Values.openelectDeployment.openelectWeb.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.openelectDeployment.openelectWeb.imagePullPolicy }}
        name: openelect-web
        ports:
        - containerPort: 8080
        resources: {}
