{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ include "chart.fullname" . }}-openelect-ingress
    labels:
    {{- include "chart.labels" . | nindent 4 }}
    annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
    ingressClassName: {{ .Values.ingress.className | default "nginx" }}
    rules:
        - host: {{ .Values.ingress.host | default "localhost" }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ include "chart.fullname" . }}-openelect-service
                            port:
                                number: {{ index .Values.openelectService.ports 0 "port" }}
        - host: adminer.{{ .Values.ingress.host | default "localhost" }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ include "chart.fullname" . }}-adminer-service
                            port:
                                number: {{ index .Values.adminerService.ports 0 "port" }}
{{- end }}
