apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ include "chart.fullname" . }}-openelect-ingress
    {{- if eq .Values.ingress.className "nginx" }}
    annotations:
        nginx.org/client-max-body-size: "4096m"
        nginx.ingress.kubernetes.io/proxy-body-size: "4096m"
    {{- end }}
spec:
    ingressClassName: {{ .Values.ingress.className | default "nginx" }}
    rules:
        {{- if eq .Values.environment "prod" }}
        - host: {{ .Values.ingress.host | default "localhost" }}
        {{- else }}
        - host: localhost
        {{- end }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ include "chart.fullname" . }}-openelect-service
                            port:
                                number: {{ index .Values.openelectService.ports 0 "port" }}
        {{- if eq .Values.environment "prod" }}
        - host: {{ .Values.ingress.adminerHost | default "localhost" }}
        {{- else }}
        - host: adminer.localhost
        {{- end }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ include "chart.fullname" . }}-adminer-service
                            port:
                                number: {{ index .Values.adminerService.ports 0 "port" }}
