apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-typesense-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.typesenseService.type }}
  selector:
    app: typesense
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.typesenseService.ports | toYaml | nindent 2 }}
