apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-openelect-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.openelectService.type }}
  selector:
    app: openelect
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.openelectService.ports | toYaml | nindent 2 }}
