apiVersion: apps/v1
kind: Deployment
metadata:
    name: openelect-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: openelect
    template:
        metadata:
            labels:
                app: openelect
        spec:
            containers:
                - name: openelect-web
                  image: openelect:latest
                  imagePullPolicy: Never
                  envFrom:
                    - configMapRef:
                        name: openelect-config
                  volumeMounts:
                    - mountPath: /app/config
                      name: colors-config
                  ports:
                      - containerPort: 8080
                - name: tailwind
                  image: tailwind
                  imagePullPolicy: Never
                  volumeMounts:
                    - mountPath: /app/config
                      name: colors-config
            volumes:
                - name: colors-config
                  emptyDir: {}