apiVersion: v1
kind: Service
metadata:
    name: typesense-service
spec:
    selector:
        app: typesense
    ports:
        - protocol: TCP
          port: 8108
          targetPort: 8108
    type: NodePort