apiVersion: apps/v1
kind: Deployment
metadata:
    name: typesense-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: typesense
    template:
        metadata:
            labels:
                app: typesense
        spec:
            containers:
                - name: typesense
                  image: typesense/typesense:27.0
                  args: ["--data-dir", "/data", "--api-key=xyz", "--enable-cors"]
                  ports:
                      - containerPort: 8108
                  volumeMounts:
                      - mountPath: /data
                        name: typesense-data
            volumes:
                - name: typesense-data
                  persistentVolumeClaim:
                      claimName: typesense-pvc