admingroup: OpenElect Admins
candidategroup: OpenElect Candidates
maxvotes: 3
positions:
    acacia house captain: Acacia
    banksia house captain: Banksia
    boronia house capatin: Boronia
    dirrum dirrum captain: ""
    house captain: ""
    huon house captain: Huon
    jarrah house captain: Jarrah
    karri house captain: Karri
    kurrajong house captain: Kurrajong
    school captain: ""
    vice captain: ""
    wandoo house captain: Wandoo
endelection: 2050-12-31