admingroup: OpenElect Admins
candidategroup: OpenElect Candidates
endelectiontime: "2025-01-09"
indeximage: https://nexus.radford.act.edu.au/storage/image.php?size=maxsize&hash=fec05ad5d7a8d76a723545c0d1485f6f727643a6
maxvotes: 3
positions:
    acacia house captain: Acacia
    banksia house captain: Banksia
    boronia house capatin: Boronia
    dirrum dirrum captain: ""
    house captain: ""
    huon house captain: Huon
    jarrah house captain: Jarrah
    karri house captain: Karri
    kurrajong house captain: Kurrajong
    school captain: ""
    vice captain: ""
    wandoo house captain: Wandoo
