admingroup: OpenElect Admins
candidategroup: OpenElect Candidates
maxvotes: 3
positions:
    - School Captain
    - Vice Captain
    - House Captain
    - Prefect
    - Dirrum Dirrum Captain
    - Acacia House Captain:
          - required_group: Acacia
    - Banksia House Captain:
          - required_group: Banksia
