name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v4
    - name: Build the Docker image - App
      run: docker build . --file Dockerfile --tag ghcr.io/radfordit/openelect/app
    - name: Build the Docker image - Tailwind
      run: docker build . --file tailwind.Dockerfile --tag ghcr.io/radfordit/openelect/tailwind
    - name: Push image - App
      run: docker push ghcr.io/radfordit/openelect/app
    - name: Push image - Tailwind
      run: docker push ghcr.io/radfordit/openelect/tailwind
