name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image - App
      run: docker build . --file Dockerfile --tag ghcr.io/radfordit/openelect-app
    - name: Build the Docker image - Tailwind
      run: docker build . --file tailwind.Dockerfile --tag ghcr.io/radfordit/openelect-tailwind
